'use strict';

// Types of Events and Event handlers
// Events -> signal generated by a certain DOM element
// Signal -> 'click', mouse moving, full screen mode, etc
// No matter if we handle a certain event, that event will always happen when the user executes it

const h1 = document.querySelector('h1');
// Attaching an Event listener onto an object
// Modern: addEventListenr -> Can add multiple Events to a same function and we can remove the Event Handler

const alertH1 = function (e) {
  alert('addEventListener: Great! You are reading the heading :D');

  // Use once
  // h1.removeEventListener('mouseenter', alertH1);
};
// mouseenter Event: Mouse hovers the Element
h1.addEventListener('mouseenter', alertH1);

// timeout
setTimeout(() => h1.removeEventListener('mouseenter', alertH1), 3000);

// Old School way to attach an Event listener to an object
// h1.onmouseenter = function (e) {
//   alert('addEventListener: Great! You are reading the heading :D');
// };

// 3rd way to attach -> Should not be used -> Added in the HTML directly
